apiVersion: v1

kind: ReplicationController

metadata:
  name: coffee-rc
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: coffee
        image: harbor.lab.local/agilderdale/nginxdemos/hello
        ports:
        - containerPort: 80
---
apiVersion: v1

kind: ReplicationController

metadata:
  name: tea-rc
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tea
    spec:
      containers:
      - name: tea
        image: harbor.lab.local/agilderdale/nginxdemos/hello
        ports:
        - containerPort: 80
